name: Node.js Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Récupération du code
      - uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20   # tu peux mettre 18 si tu veux rester sur 18
          cache: 'npm'       # cache node_modules pour accélérer les builds

      # 3️⃣ Installation des dépendances
      - name: Install dependencies
        run: npm install

      # 4️⃣ Linter le code
      - name: Run ESLint
        run: npm run lint

      # 5️⃣ Lancer les tests Jest
      - name: Run tests
        run: npm test

  docker-build:
    runs-on: ubuntu-latest
    needs: lint-test   # build uniquement si lint + test réussis
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t docker-ci-node .
          docker images
