name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'      # ou la version de Node de ton projet
          cache: 'npm'            # cache des node_modules pour accélérer le workflow

      # 3️⃣ Installer les dépendances
      - name: Install dependencies
        run: npm install

      # 4️⃣ Linter le code avec ESLint
      - name: Run ESLint
        run: npx eslint .        # utilise le binaire local ESLint

      # 5️⃣ Lancer les tests Jest
      - name: Run Jest tests
        run: npm test

      # 6️⃣ Optionnel : afficher les versions
      - name: Node and npm versions
        run: |
          node -v
          npm -v
